const $=id=>document.getElementById(id);const invoke=window.__TAURI__?.core.invoke;
let installed=false,enabled=false,busy=false,page='overview',range='today',custom=null,lastTotal=null,lastTime=null,polling=false,lastFlows=[];
function notice(s){$('notice').textContent=s;$('notice').hidden=!s}
function bytes(n){if(!Number.isFinite(n))return '—';const units=['B','KiB','MiB','GiB','TiB'];let i=0;while(n>=1024&&i<4){n/=1024;i++}return `${n.toFixed(i?2:0)} ${units[i]}`}
function number(r,k){return Number(r[k]||0)}
function sums(r){const v6=number(r,'v6_up')+number(r,'v6_down'),v4=number(r,'v4_up')+number(r,'v4_down');return {v6,v4,total:v6+v4,up:number(r,'v4_up')+number(r,'v6_up'),down:number(r,'v4_down')+number(r,'v6_down')}}
function date(ts){return new Date(ts*1000).toLocaleString('zh-CN',{hour12:false})}
async function call(action,args={}){if(!invoke)throw Error('请在 V6Only 桌面应用中打开，浏览器预览不能控制后台服务。');return invoke('service',{action,...args})}
function setControl(){const b=$('control');b.disabled=busy;b.textContent=busy?'正在配置…':!installed?'安装并启用':enabled?'关闭转发':'启用转发'}
function showPage(p){page=p;for(const x of document.querySelectorAll('.page'))x.hidden=x.id!==p;for(const b of document.querySelectorAll('nav button'))b.classList.toggle('selected',b.dataset.page===p);$('page-title').textContent={overview:'网络概览',traffic:'流量记录',diagnose:'连接检测',logs:'运行日志'}[p];if(p==='traffic'&&installed)loadRange()}
for(const b of document.querySelectorAll('nav button'))b.addEventListener('click',()=>showPage(b.dataset.page));for(const b of document.querySelectorAll('[data-goto]'))b.onclick=()=>showPage(b.dataset.goto);
const reasons={chatgpt_ipv4_proxy:'ChatGPT IPv4 代理',ipv6_required:'域名有 IPv6',ipv6_response:'IPv6 已响应',no_aaaa:'仅 IPv4 目标',literal_ipv4:'裸地址 / 域名未识别',literal_or_unidentified_ipv4:'裸地址 / 域名未识别',udp_response_pending:'UDP 等待响应'};
function renderFlows(flows){lastFlows=flows||[];const body=$('flows-body');body.replaceChildren();const selected=lastFlows.filter(f=>$('flow-filter').value==='all'||/bilibili|bilivideo|biliapi|hdslb|bilicdn/.test(f.host)).sort((a,b)=>(b.upload_bytes+b.download_bytes)-(a.upload_bytes+a.download_bytes)).slice(0,12);if(!selected.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=4;td.className='empty';td.textContent='暂无符合条件的连接';tr.append(td);body.append(tr);return}for(const f of selected){const tr=document.createElement('tr');const ipv6=f.network?.endsWith('6');for(const [i,v]of [f.host,f.remote,ipv6?'IPv6':f.reason==='chatgpt_ipv4_proxy'?'IPv4 代理':'IPv4',`↑ ${bytes(f.upload_bytes||0)} / ↓ ${bytes(f.download_bytes||0)}`].entries()){const td=document.createElement('td');if(i===2){const b=document.createElement('span');b.className='protocol'+(ipv6?'':' ipv4');b.textContent=v;td.append(b)}else td.textContent=v;tr.append(td)}body.append(tr)}}
$('flow-filter').onchange=()=>renderFlows(lastFlows);
function renderStatus(s){installed=s.installed;enabled=s.enabled;const verified=s.health?.data_path_verified;const good=enabled&&verified;$('header-state').textContent=good?'转发运行中':enabled?'正在验证链路':'转发未启用';$('state-dot').classList.toggle('on',good);$('connection-title').textContent=good?'已连接':enabled?'正在连接':'当前使用系统默认网络';$('connection-detail').textContent=good?'正在记录流量。':enabled?'请稍候。':s.suspended?'已暂停。':'连接后开始记录流量。';$('core-status').textContent=enabled?'运行中':'未运行';$('path-status').textContent=verified?'已验证':'尚未验证';$('interface-status').textContent=s.ipv6_interface?.match(/inet6 ([23][0-9a-f:]+)/i)?'可用':'暂无全球 IPv6 地址';$('proxy-status').textContent=s.pac?.includes('http://127.0.0.1:17890/proxy.pac')&&s.pac?.includes('Enabled: Yes')?'已开启':s.proxy?.includes('Enabled: Yes')?'已开启':'已关闭';$('last-update').textContent=new Date().toLocaleTimeString('zh-CN',{hour12:false});$('logs-text').textContent=s.logs||'暂无日志';renderFlows(s.flows);setControl()}
function renderAll(r){const a=sums(r);$('all-total').textContent=bytes(a.total);$('all-v6').textContent=bytes(a.v6);$('all-v4').textContent=bytes(a.v4);$('all-v6-detail').textContent=`↑ ${bytes(r.v6_up)}　↓ ${bytes(r.v6_down)}`;$('all-v4-detail').textContent=`↑ ${bytes(r.v4_up)}　↓ ${bytes(r.v4_down)}`;$('share-v6-bytes').textContent=bytes(a.v6);$('share-v4-bytes').textContent=bytes(a.v4);const share=a.total?a.v6/a.total:0;document.querySelector('.donut').classList.toggle('no-data',!a.total);$('v6-share').textContent=a.total?(share*100).toFixed(1)+'%':'—';$('donut-v6').style.strokeDasharray=`${share*302} 302`;$('record-start').textContent=r.started_at?`记录始于 ${date(r.started_at)}`:'尚未开始记录';const now=Date.now();if(lastTotal!==null&&lastTime&&a.total>=lastTotal)$('current-rate').textContent=bytes((a.total-lastTotal)/((now-lastTime)/1000))+'/s';lastTotal=a.total;lastTime=now}
function getRange(){const now=Math.floor(Date.now()/1000)+1;if(range==='custom'&&custom)return custom;let start=new Date();if(range==='today')start.setHours(0,0,0,0);else if(range==='week')start=new Date((now-7*86400)*1000);else if(range==='month')start=new Date((now-30*86400)*1000);else return {from:0,to:now};return {from:Math.floor(start.getTime()/1000),to:now}}
function renderRange(r){const a=sums(r);$('range-total').textContent=bytes(a.total);$('range-v6').textContent=bytes(a.v6);$('range-v4').textContent=bytes(a.v4);$('range-up-down').textContent=`↑ ${bytes(a.up)}　↓ ${bytes(a.down)}`;$('range-v6-detail').textContent=`↑ ${bytes(r.v6_up)}　↓ ${bytes(r.v6_down)}`;$('range-v4-detail').textContent=`↑ ${bytes(r.v4_up)}　↓ ${bytes(r.v4_down)}`;$('range-caption').textContent=`${date(r.from||r.started_at)} → ${date(r.to)}`;$('export').disabled=!r.points?.length;drawChart(r)}
function drawChart(r){const container=$('chart');container.replaceChildren();if(!r.points?.length){const d=document.createElement('div');d.className='chart-empty';d.textContent='这个时段暂无流量记录';container.append(d);return}const start=Math.max(r.from,r.started_at),duration=Math.max(r.to-start,1),bins=48,step=Math.max(Math.ceil(duration/bins),r.resolution);const n=Math.ceil(duration/step);const values=Array.from({length:n},()=>({v4:0,v6:0}));for(const p of r.points){const i=Math.max(0,Math.min(n-1,Math.floor((p.at-start)/step)));const s=sums(p);values[i].v4+=s.v4;values[i].v6+=s.v6}const max=Math.max(...values.map(p=>p.v4+p.v6),1),w=800,h=190,left=65,bottom=27,top=12,plot=h-bottom-top,bw=(w-left-10)/n;const NS='http://www.w3.org/2000/svg';const svg=document.createElementNS(NS,'svg');svg.setAttribute('viewBox',`0 0 ${w} ${h}`);function el(tag,attrs,text){const e=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);if(text)e.textContent=text;svg.append(e);return e}for(let i=0;i<4;i++){const y=top+plot*i/3;el('line',{x1:left,x2:w-8,y1:y,y2:y,stroke:'#e4eaf3'});el('text',{x:0,y:y+4},bytes(max*(1-i/3)))}for(let i=0;i<n;i++){const p=values[i],v6=p.v6/max*plot,v4=p.v4/max*plot;for(const[ht,y,color]of [[v4,top+plot-v4,'#bd651d'],[v6,top+plot-v4-v6,'#087c74']]){const b=el('rect',{x:left+i*bw+1,y,width:Math.max(bw-3,1),height:ht,fill:color,rx:2});const title=document.createElementNS(NS,'title');title.textContent=`${date(start+i*step)}：IPv6 ${bytes(p.v6)} / IPv4 ${bytes(p.v4)}`;b.append(title)}}for(const[f,anchor]of [[0,'start'],[.5,'middle'],[1,'end']])el('text',{x:left+(w-left-10)*f,y:h-5,'text-anchor':anchor},new Date((start+duration*f)*1000).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}));container.append(svg)}
async function loadRange(){try{const r=await call('stats',getRange());renderRange(r)}catch(e){$('range-caption').textContent=String(e)}}
async function refresh(){if(polling||busy||document.hidden)return;polling=true;try{const s=await call('status');renderStatus(s);try{renderAll(await call('stats',{from:0,to:Math.floor(Date.now()/1000)+1}));if(page==='traffic')await loadRange()}catch(e){$('record-start').textContent='尚无记录：首次启用后开始累计';$('range-caption').textContent=String(e)}}catch(e){installed=false;enabled=false;$('header-state').textContent='需要安装后台服务';$('connection-title').textContent='尚未连接';$('connection-detail').textContent='首次安装需要 系统管理员授权。此后可直接开启、关闭与检测。';$('core-status').textContent='尚未安装';$('path-status').textContent='尚未验证';$('logs-text').textContent=String(e);setControl()}finally{polling=false}}
$('control').onclick=async()=>{busy=true;setControl();notice('');try{if(!installed){await invoke('install_service')}else await call(enabled?'disable':'enable')}catch(e){notice(String(e))}finally{busy=false;setControl();await refresh()}};
$('refresh').onclick=$('refresh-logs').onclick=()=>refresh();
for(const b of document.querySelectorAll('[data-range]'))b.onclick=()=>{range=b.dataset.range;for(const x of document.querySelectorAll('[data-range]'))x.classList.toggle('active',x===b);$('custom-range').hidden=range!=='custom';if(range!=='custom')loadRange()};
function inputDate(d){return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,19)}$('range-from').value=inputDate(new Date(new Date().setHours(0,0,0,0)));$('range-to').value=inputDate(new Date());
$('apply-range').onclick=()=>{const from=Math.floor(new Date($('range-from').value).getTime()/1000),to=Math.floor(new Date($('range-to').value).getTime()/1000);if(!Number.isFinite(from)||!Number.isFinite(to)||to<=from){notice('结束时间须晚于开始时间。');return}custom={from,to};notice('');loadRange()};
$('export').onclick=async()=>{try{const path=await invoke('save_export',getRange());notice(`CSV 已保存：${path}`)}catch(e){notice(String(e))}};
$('diagnostic-form').onsubmit=async e=>{e.preventDefault();const button=$('diagnostic-button');button.disabled=true;button.textContent='正在检测…';const container=$('diagnostic-result');container.hidden=true;notice('');try{const r=await call('diagnose',{url:$('diagnostic-url').value.trim()});container.replaceChildren();const panel=document.createElement('div');panel.className='diagnostic-summary'+(r.error?' failed':'');const h=document.createElement('h3');h.textContent=r.error?'连接未成功':`连接成功 · HTTP ${r.http_status}`;panel.append(h);for(const text of [...(r.error?[r.error]:[]),`耗时 ${r.duration_ms??0} ms`,...(r.flows||[]).map(f=>`${f.network.endsWith('6')?'IPv6':'IPv4'} → ${f.remote}`)]){const p=document.createElement('p');p.textContent=text;panel.append(p)}container.append(panel);const dns=document.createElement('div');dns.className='dns-grid';for(const[label,records]of [['IPv6 地址',r.aaaa],['IPv4 地址',r.a]]){const d=document.createElement('div'),h=document.createElement('h3'),p=document.createElement('pre');h.textContent=label;p.textContent=records?.length?records.join('\n'):'无记录';d.append(h,p);dns.append(d)}container.append(dns);container.hidden=false}catch(e){notice(String(e))}finally{button.disabled=false;button.textContent='开始检测'}};
refresh();setInterval(refresh,5000);
